apiVersion: v2
name: gameserver
description: 高性能分布式游戏服务器框架 Helm Chart
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - gameserver
  - distributed
  - microservices
  - spring-boot
home: https://github.com/liuxiao2015/game-server-framework
sources:
  - https://github.com/liuxiao2015/game-server-framework
maintainers:
  - name: liuxiao2015
    email: liuxiao2015@example.com
    url: https://github.com/liuxiao2015
dependencies:
  - name: mysql
    version: 9.4.6
    repository: https://charts.bitnami.com/bitnami
    condition: mysql.enabled
  - name: redis
    version: 17.3.7
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: nginx
    version: 13.2.9
    repository: https://charts.bitnami.com/bitnami
    condition: nginx.enabled
annotations:
  category: GameServer
  licenses: Apache-2.0