# 游戏服务器数据库配置示例
# 用途: 提供数据库配置模板和参考
# 说明: 包含主从库配置、连接池参数、分库分表配置等

# 数据库配置
game:
  database:
    # 是否启用数据库功能
    enabled: true
    
    # 主数据库配置
    master:
      url: jdbc:mysql://localhost:3306/gamedb_master?useUnicode=true&characterEncoding=utf8mb4&useSSL=false&serverTimezone=Asia/Shanghai
      username: root
      password: password
      driver-class-name: com.mysql.cj.jdbc.Driver
      enabled: true
      weight: 1
    
    # 从数据库配置
    slaves:
      - url: jdbc:mysql://localhost:3307/gamedb_slave1?useUnicode=true&characterEncoding=utf8mb4&useSSL=false&serverTimezone=Asia/Shanghai
        username: root
        password: password
        driver-class-name: com.mysql.cj.jdbc.Driver
        enabled: true
        weight: 1
      - url: jdbc:mysql://localhost:3308/gamedb_slave2?useUnicode=true&characterEncoding=utf8mb4&useSSL=false&serverTimezone=Asia/Shanghai
        username: root
        password: password
        driver-class-name: com.mysql.cj.jdbc.Driver
        enabled: true
        weight: 2
    
    # 连接池配置
    pool:
      # 最大连接数
      maximum-pool-size: 20
      # 最小空闲连接数
      minimum-idle: 5
      # 连接超时时间
      connection-timeout: 30s
      # 空闲超时时间
      idle-timeout: 10m
      # 最大生命周期
      max-lifetime: 30m
      # 连接泄露检测阈值
      leak-detection-threshold: 60s
      # 预编译语句缓存
      prep-stmt-cache-size: true
      prep-stmt-cache-sql-limit: 2048
      use-server-prep-stmts: true
      rewrite-batched-statements: true
    
    # 分库分表配置
    sharding:
      # 是否启用分库分表
      enabled: false
      # 数据库分片数量
      database-sharding-count: 2
      # 表分片数量
      table-sharding-count: 4
      # 分片算法类型
      sharding-algorithm: mod
    
    # 监控配置
    monitor:
      # 是否启用监控
      enabled: true
      # 慢查询阈值(毫秒)
      slow-query-threshold: 1000
      # 指标采集间隔(秒)
      metrics-interval: 60
      # 健康检查间隔(秒)
      health-check-interval: 10

---
# 开发环境配置
spring:
  profiles: dev

game:
  database:
    # 开发环境使用H2内存数据库
    master:
      url: jdbc:h2:mem:gamedb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MySQL
      username: sa
      password: 
      driver-class-name: org.h2.Driver
    
    # 开发环境不配置从库
    slaves: []
    
    pool:
      maximum-pool-size: 10
      minimum-idle: 2

---
# 测试环境配置
spring:
  profiles: test

game:
  database:
    master:
      url: jdbc:mysql://test-mysql:3306/gamedb_test?useUnicode=true&characterEncoding=utf8mb4&useSSL=false&serverTimezone=Asia/Shanghai
      username: test_user
      password: test_password
    
    slaves: []
    
    pool:
      maximum-pool-size: 15
      minimum-idle: 3

---
# 生产环境配置
spring:
  profiles: prod

game:
  database:
    master:
      url: jdbc:mysql://prod-mysql-master:3306/gamedb_prod?useUnicode=true&characterEncoding=utf8mb4&useSSL=false&serverTimezone=Asia/Shanghai
      username: ${DB_USERNAME:prod_user}
      password: ${DB_PASSWORD:prod_password}
    
    slaves:
      - url: jdbc:mysql://prod-mysql-slave1:3306/gamedb_prod?useUnicode=true&characterEncoding=utf8mb4&useSSL=false&serverTimezone=Asia/Shanghai
        username: ${DB_USERNAME:prod_user}
        password: ${DB_PASSWORD:prod_password}
        weight: 1
      - url: jdbc:mysql://prod-mysql-slave2:3306/gamedb_prod?useUnicode=true&characterEncoding=utf8mb4&useSSL=false&serverTimezone=Asia/Shanghai
        username: ${DB_USERNAME:prod_user}
        password: ${DB_PASSWORD:prod_password}
        weight: 2
    
    pool:
      maximum-pool-size: 50
      minimum-idle: 10
      connection-timeout: 20s
      idle-timeout: 15m
      max-lifetime: 45m
    
    sharding:
      enabled: true
      database-sharding-count: 4
      table-sharding-count: 8
    
    monitor:
      slow-query-threshold: 500
      metrics-interval: 30